import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { TanstackQueryClientProvider } from "@/components/providers/TanstackQueryClientProvider";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <TanstackQueryClientProvider>
            <ThemeProvider
              attribute={"class"}
              defaultTheme="light"
              enableSystem={false}
            >
              <div className="fixed top-0 left-0 w-full z-10 backdrop-blur-md  bg-slate-100/70 dark:bg-slate-800/70">
                <Header />
              </div>
              <div className="pt-12">{children}</div>
              <Toaster position="top-center" richColors />
            </ThemeProvider>
          </TanstackQueryClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
